Operação de união de AFDs concluída.
Clovijan/uniao_afd_afn pull request #13
Opened 2023-04-18 18:14 UTC by j0ng4b

A união pode ser feita independentemente do AFD ser completo ou não, para isso o código sofreu algumas alterações para poder facilitar a adição de estados consumidores para poder completar o autômato.

O autômato resultante gera inúmeros estados inalcançáveis seria uma boa remover esses estados. Outra possível melhoria é renomear para um nome simples os estados, por exemplo:
    q0q4 -> q5
    q8q10 -> q0

Fecha #12 e completa #9.

2023-04-26 12:00 UTC, Gabrielx47 requested changes
Por favor, veja a possibilidade de realizar as mudanças. Além disso, faça um pull da master para a sua branch, isto vai evitar que haja conflitos no momento do merge da PR.

2023-04-26 12:00 UTC, Gabrielx47 commented on src/Automato.java
> +        // Adiciona um estado consumidor e suas transições
No entanto, você poderia adiciona um IF para verificar se o autômato é completo. Lembre-se que já existe uma função para realizar a verificação, basta adiciona o if e pronto.

2023-04-28 10:43 UTC, Gabrielx47 requested changes
Veja os comentários e avalie o ponto que comentei.

2023-04-28 10:43 UTC, Gabrielx47 commented on src/Automato.java
> +            automato2.addEstado(new Estado("d", 0));
Verifique se cada autômato é completo separadamente, pois se um dos dois for completo, todos seram completados e isto não é o correto. Por favor, corrigar esse problema.

2023-04-28 10:43 UTC, Gabrielx47 commented on src/Automato.java
> +            automato2.addEstado(new Estado("d", 0));
Coloque um IF para cada autômato.

2023-04-28 16:36 UTC, j0ng4b commented on src/Automato.java
> +            automato2.addEstado(new Estado("d", 0));
> Verifique se cada autômato é completo separadamente, pois se um dos dois for completo, todos seram completados e isto não é o correto. Por favor, corrigar esse problema.

Bom, isso não faria diferença no final do processo, só geraria estados inalcançáveis que com um pós-processamento seriam removido.

De qualquer forma está feito.

2023-04-28 16:50 UTC, Gabrielx47 approved these changes
Código está funcionando corretamente.

2023-04-28 16:50 UTC, merged